[project]
name = "MON"
version = "0.1.0"
description = "Minimum Operational Network"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas",
    "geographiclib",
    "openpyxl",
    "requests",
    "isort",
    "pyarrow",
    "plotly",
]

[project.scripts]
mon = "mon:main"

[tool.uv]
package = true

[tool.setuptools]
py-modules = ["mon"]
